/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BaklavaRouteImport } from './routes/baklava'
import { Route as CareRouteImport } from './routes/care'
import { Route as KunafaRouteImport } from './routes/kunafa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BaklavaRoute = BaklavaRouteImport.update({
  id: '/baklava',
  path: '/baklava',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const KunafaRoute = KunafaRouteImport.update({
  id: '/kunafa',
  path: '/kunafa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baklava': typeof BaklavaRoute
  '/care': typeof CareRoute
  '/kunafa': typeof KunafaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baklava': typeof BaklavaRoute
  '/care': typeof CareRoute
  '/kunafa': typeof KunafaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baklava': typeof BaklavaRoute
  '/care': typeof CareRoute
  '/kunafa': typeof KunafaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/baklava' | '/care' | '/kunafa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/baklava' | '/care' | '/kunafa'
  id: '__root__' | '/' | '/about' | '/baklava' | '/care' | '/kunafa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BaklavaRoute: typeof BaklavaRoute
  CareRoute: typeof CareRoute
  KunafaRoute: typeof KunafaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baklava': {
      id: '/baklava'
      path: '/baklava'
      fullPath: '/baklava'
      preLoaderRoute: typeof BaklavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunafa': {
      id: '/kunafa'
      path: '/kunafa'
      fullPath: '/kunafa'
      preLoaderRoute: typeof KunafaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BaklavaRoute: BaklavaRoute,
  CareRoute: CareRoute,
  KunafaRoute: KunafaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
